<?php
namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
  public function createFindOneByIdQuery($id)
  {
      $query = $this->_em->createQuery(
          "
          SELECT p
          FROM AppBundle:Product p
          WHERE p.id = :id
          "
      );
      $query->setParameter('id', $id);
      return $query;
  }
}
